//! C99/C11 Native Backend & Hardware Driver Scaffolding Generator.
//! Implements Section 11 (Lowering Universal HIR to Native Execution)
//! and Section 12 (Hardware Definition Language, Drivers, C Interop, and OS Integration).

use crate::ast::{Expr, FnDecl, Program, Stmt, TypeSpec};
use crate::hir::{HirInstruction, UniversalHirModule};

pub fn generate_c_code(prog: &Program, hir: &UniversalHirModule) -> String {
    let mut c = Vec::new();

    c.push("/* ==========================================================================".to_string());
    c.push(" * Generated by the HWCode Compiler (Rust Stage-0 -> Universal HIR -> C11)".to_string());
    c.push(" * Physical Boundaries: Verified (Memory, Layout, Ownership, Clock, State, Power)".to_string());
    c.push(" * ========================================================================== */".to_string());
    c.push("#include <stdio.h>".to_string());
    c.push("#include <stdint.h>".to_string());
    c.push("#include <stdbool.h>".to_string());
    c.push("".to_string());

    // Embedded Zero-Overhead HWCode Hardware Runtime Shim
    c.push("/* --- HWCode Hardware Runtime Primitives --- */".to_string());
    c.push("static inline void hwcode_rt_domain_alloc(const char* var, const char* dom, const char* ty, const char* lay, size_t bytes) {".to_string());
    c.push("    printf(\"[HWCode RT] DOMAIN_ALLOC     %s : %s<%s>(%s) [%zu bytes]\\n\", var, dom, ty, lay, bytes);".to_string());
    c.push("}".to_string());
    c.push("static inline void hwcode_rt_acquire(const char* var, const char* ep, const char* mode) {".to_string());
    c.push("    printf(\"[HWCode RT] RESOURCE_ACQUIRE %s = acquire(%s, %s)\\n\", var, ep, mode);".to_string());
    c.push("}".to_string());
    c.push("static inline void hwcode_rt_release(const char* var, const char* ep) {".to_string());
    c.push("    printf(\"[HWCode RT] RESOURCE_RELEASE release(%s @ %s)\\n\", var, ep);".to_string());
    c.push("}".to_string());
    c.push("static inline void hwcode_rt_route(int id, const char* path, const char* proto, const char* payload, double bw_gbps, unsigned long lat_ns) {".to_string());
    c.push("    printf(\"[HWCode RT] ROUTE #%d         %s [%s] payload=%s (%.1f GB/s, %lu ns)\\n\", id, path, proto, payload, bw_gbps, lat_ns);".to_string());
    c.push("}".to_string());
    c.push("static inline void hwcode_rt_memory_barrier(const char* order, const char* from_dom, const char* to_dom) {".to_string());
    c.push("    printf(\"[HWCode RT] MEMORY_BARRIER   order=%s (%s -> %s)\\n\", order, from_dom, to_dom);".to_string());
    c.push("}".to_string());
    c.push("static inline void hwcode_rt_dma(const char* eng, const char* src, const char* dst, const char* payload, size_t bytes) {".to_string());
    c.push("    printf(\"[HWCode RT] DMA              engine=%s %s -> %s : %s (%zu bytes)\\n\", eng, src, dst, payload, bytes);".to_string());
    c.push("}".to_string());
    c.push("static inline void hwcode_rt_layout_convert(const char* buf, const char* from_l, const char* to_l, const char* mech, unsigned long cost_ns) {".to_string());
    c.push("    printf(\"[HWCode RT] LAYOUT_CONVERT   %s : %s ==> %s via %s (+%lu ns)\\n\", buf, from_l, to_l, mech, cost_ns);".to_string());
    c.push("}".to_string());
    c.push("static inline void hwcode_rt_clock_sync(const char* sig, const char* from_c, const char* to_c, const char* prim, unsigned int cycles) {".to_string());
    c.push("    printf(\"[HWCode RT] CLOCK_SYNC       %s (%s -> %s) via %s (%u cycles)\\n\", sig, from_c, to_c, prim, cycles);".to_string());
    c.push("}".to_string());
    c.push("static inline void hwcode_rt_state_transition(const char* dev, const char* cls, const char* from_s, const char* to_s, const char* trig) {".to_string());
    c.push("    printf(\"[HWCode RT] STATE_TRANSITION %s (%s) : %s -> %s [on %s]\\n\", dev, cls, from_s, to_s, trig);".to_string());
    c.push("}".to_string());
    c.push("static inline void hwcode_rt_device_cmd(const char* dev, const char* ep, const char* cmd, const char* state) {".to_string());
    c.push("    printf(\"[HWCode RT] DEVICE_COMMAND   %s.%s() @ %s [verified_state=%s]\\n\", dev, cmd, ep, state);".to_string());
    c.push("}".to_string());
    c.push("static inline void hwcode_rt_budget(const char* var, double alloc_w, double rem_w) {".to_string());
    c.push("    printf(\"[HWCode RT] BUDGET_ACCOUNT   %s -= %.1fW (remaining=%.1fW)\\n\", var, alloc_w, rem_w);".to_string());
    c.push("}".to_string());
    c.push("static inline void hwcode_rt_trace(const char* label) {".to_string());
    c.push("    printf(\"[HWCode RT] TRACE_POINT      \\\"%s\\\"\\n\", label);".to_string());
    c.push("}".to_string());
    c.push("".to_string());

    // Emit structs
    for st in &prog.structs {
        c.push(format!("typedef struct {} {{", st.name));
        for (fname, fty) in &st.fields {
            c.push(format!("    {} {};", map_c_type(fty), fname));
        }
        c.push(format!("}} {};\n", st.name));
    }

    // Emit user pure functions (except `main`, which we merge with the HIR execution plan)
    for func in &prog.functions {
        if func.name != "main" {
            c.push(emit_c_function(func));
        }
    }

    // Emit the lowered Universal HIR physical execution plan function
    c.push("void hwcode_execute_physical_plan(void) {".to_string());
    for inst in &hir.instructions {
        match inst {
            HirInstruction::DomainAlloc {
                var_name,
                domain,
                semantic_type,
                layout,
                bytes,
            } => {
                c.push(format!(
                    "    hwcode_rt_domain_alloc(\"{}\", \"{}\", \"{}\", \"{}\", {});",
                    var_name, domain, semantic_type, layout, bytes
                ));
            }
            HirInstruction::ResourceAcquire {
                dest_var,
                endpoint,
                mode,
            } => {
                c.push(format!(
                    "    hwcode_rt_acquire(\"{}\", \"{}\", \"{}\");",
                    dest_var, endpoint, mode
                ));
            }
            HirInstruction::ResourceRelease { var_name, endpoint } => {
                c.push(format!(
                    "    hwcode_rt_release(\"{}\", \"{}\");",
                    var_name, endpoint
                ));
            }
            HirInstruction::Route {
                route_id,
                planned,
                payload,
            } => {
                c.push(format!(
                    "    hwcode_rt_route({}, \"{}\", \"{}\", \"{}\", {:.1}, {}UL);",
                    route_id,
                    planned.format_path(),
                    planned.protocols.join("+"),
                    payload,
                    planned.effective_bandwidth_gbps,
                    planned.total_latency_ns
                ));
            }
            HirInstruction::MemoryBarrier {
                ordering,
                domain_from,
                domain_to,
            } => {
                c.push(format!(
                    "    hwcode_rt_memory_barrier(\"{}\", \"{}\", \"{}\");",
                    ordering, domain_from, domain_to
                ));
            }
            HirInstruction::Dma {
                engine,
                src_endpoint,
                dst_endpoint,
                payload,
                bytes,
                ..
            } => {
                c.push(format!(
                    "    hwcode_rt_dma(\"{}\", \"{}\", \"{}\", \"{}\", {});",
                    engine, src_endpoint, dst_endpoint, payload, bytes
                ));
            }
            HirInstruction::LayoutConvert {
                buffer,
                from_layout,
                to_layout,
                mechanism,
                estimated_cost_ns,
                ..
            } => {
                c.push(format!(
                    "    hwcode_rt_layout_convert(\"{}\", \"{}\", \"{}\", \"{}\", {}UL);",
                    buffer, from_layout, to_layout, mechanism, estimated_cost_ns
                ));
            }
            HirInstruction::ClockSync {
                signal,
                from_domain,
                to_domain,
                primitive,
                latency_cycles,
            } => {
                c.push(format!(
                    "    hwcode_rt_clock_sync(\"{}\", \"{}\", \"{}\", \"{}\", {}U);",
                    signal, from_domain, to_domain, primitive, latency_cycles
                ));
            }
            HirInstruction::StateTransition {
                device_var,
                device_class,
                from_state,
                to_state,
                trigger,
            } => {
                c.push(format!(
                    "    hwcode_rt_state_transition(\"{}\", \"{}\", \"{}\", \"{}\", \"{}\");",
                    device_var, device_class, from_state, to_state, trigger
                ));
            }
            HirInstruction::DeviceCommand {
                device_var,
                endpoint,
                command,
                verified_state,
            } => {
                c.push(format!(
                    "    hwcode_rt_device_cmd(\"{}\", \"{}\", \"{}\", \"{}\");",
                    device_var, endpoint, command, verified_state
                ));
            }
            HirInstruction::BudgetAccount {
                budget_var,
                allocated_watts,
                remaining_watts,
            } => {
                c.push(format!(
                    "    hwcode_rt_budget(\"{}\", {:.1}, {:.1});",
                    budget_var, allocated_watts, remaining_watts
                ));
            }
            HirInstruction::TracePoint { label } => {
                c.push(format!("    hwcode_rt_trace(\"{}\");", label));
            }
            _ => {}
        }
    }
    c.push("}\n".to_string());

    // Emit `main` entry point
    c.push("int main(void) {".to_string());
    c.push("    hwcode_execute_physical_plan();".to_string());
    c.push("    return 0;".to_string());
    c.push("}".to_string());

    c.join("\n")
}

fn map_c_type(ty: &TypeSpec) -> &'static str {
    match ty.base_type.as_str() {
        "i8" => "int8_t",
        "i16" => "int16_t",
        "i32" => "int32_t",
        "i64" => "int64_t",
        "u8" => "uint8_t",
        "u16" => "uint16_t",
        "u32" => "uint32_t",
        "u64" => "uint64_t",
        "f32" => "float",
        "f64" => "double",
        "bool" => "bool",
        _ => "int32_t",
    }
}

fn emit_c_function(func: &FnDecl) -> String {
    let ret_ty = func
        .return_type
        .as_ref()
        .map(map_c_type)
        .unwrap_or("void");
    let params = if func.params.is_empty() {
        "void".to_string()
    } else {
        func.params
            .iter()
            .map(|(n, t)| format!("{} {}", map_c_type(t), n))
            .collect::<Vec<_>>()
            .join(", ")
    };

    let mut lines = Vec::new();
    lines.push(format!("{} {}({}) {{", ret_ty, func.name, params));
    for stmt in &func.body {
        if let Stmt::Return { value: Some(expr), .. } = stmt {
            lines.push(format!("    return {};", emit_c_expr(expr)));
        }
    }
    if lines.len() == 1 && ret_ty != "void" {
        lines.push("    return 0;".to_string());
    }
    lines.push("}\n".to_string());
    lines.join("\n")
}

fn emit_c_expr(expr: &Expr) -> String {
    match expr {
        Expr::Int(v, _, _) => v.to_string(),
        Expr::Float(v, _, _) => format!("{}", v),
        Expr::Var(s, _) => s.clone(),
        Expr::Binary {
            op, left, right, ..
        } => format!("({} {} {})", emit_c_expr(left), op, emit_c_expr(right)),
        Expr::Call {
            receiver: None,
            func,
            args,
            ..
        } => {
            let arg_list = args.iter().map(emit_c_expr).collect::<Vec<_>>().join(", ");
            format!("{}({})", func, arg_list)
        }
        _ => "0".to_string(),
    }
}

/// Generates state-safe HWCode Driver Scaffolding from `device` definitions (Section 7 & 12).
pub fn generate_driver_scaffold(prog: &Program) -> String {
    let mut out = Vec::new();
    out.push("// ============================================================================".to_string());
    out.push("// Auto-Generated HWCode State-Safe Hardware Driver Scaffolding (Section 12)".to_string());
    out.push("// ============================================================================\n".to_string());

    for dev in &prog.devices {
        let bus = dev.bus.as_deref().unwrap_or("MMIO");
        let clk = dev.clock_domain.as_deref().unwrap_or("DEV_CLK");
        let init_state = dev.initial_state.as_deref().unwrap_or("Idle");

        out.push(format!(
            "// Device: `{}` | Bus: `{}` | Clock Domain: `{}` | Initial State: `{}`",
            dev.name, bus, clk, init_state
        ));
        out.push(format!("struct {}Registers {{", dev.name));
        for (rname, rty) in &dev.registers {
            out.push(format!("    {}: MMIO<{}>,", rname, rty));
        }
        out.push("}\n".to_string());

        // Generate state-transition functions
        for (from_s, to_s, trig) in &dev.transitions {
            let fn_name = format!(
                "{}_transition_{}_to_{}",
                dev.name.to_lowercase(),
                from_s.to_lowercase(),
                to_s.to_lowercase()
            );
            out.push(format!(
                "// State Transition: {}<{}> -> {}<{}> triggered by `{}`",
                dev.name, from_s, dev.name, to_s, trig
            ));
            out.push(format!(
                "fn {}(dev: Device<{}, {}>) -> Device<{}, {}> {{",
                fn_name, dev.name, from_s, dev.name, to_s
            ));
            out.push(format!("    dev.{};", trig));
            out.push("    return dev;".to_string());
            out.push("}\n".to_string());
        }

        // Generate state-constrained operation wrappers
        for (op_name, req_state) in &dev.operations {
            out.push(format!(
                "// Operation `{}` statically requires state `{}`",
                op_name, req_state
            ));
            out.push(format!(
                "fn {}_{}(dev: &Device<{}, {}>) -> f32 {{",
                dev.name.to_lowercase(),
                op_name,
                dev.name,
                req_state
            ));
            out.push(format!("    return dev.{}();", op_name));
            out.push("}\n".to_string());
        }
    }

    out.join("\n")
}
